[package]
name = "lux-keys-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "lux_keys_macros"

[dependencies]
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = { version = "2.0.87", features = ["full"] }
